### ISSUE TITLE
example not working

### ISSUE THREAD

**Issue by mmaestrini** [williamjuan027/nativescript-movies-demo#5]
Tried to run on ios like in readme and i get the following:

Package subpath './package.json' is not defined by "exports" in /Users/xxxxxxxxxx/Programming/Boilerplates/demo nativescript movie/nativescript-movies-demo/node_modules/popmotion/package.json

What's the problem?

**Comment by williamjuan027** [comment]
@mmaestrini That seems to be a problem with npm/node. Can you try running it with npm 7.x.x and node 12.x.x
I personally use npm 7.7.5 and node 12.7.0.

Let me know if that works for you :)

**Comment by mmaestrini** [comment]
works with those versions.. :)
